# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24e7d8985a8f4abf2524f9522af8812d9f72332f97bf4ccd80b46bacacaa74efb2e1f446b50f5d1001a8f0fa669b10deeb20e72d8d194fe7b0fb348988c9667

test:
  secret_key_base: b3a50f4494243d3bde318b5f1cb248d1cce08cf4b0c76c1b6724a41d8b61421302e1dd8a05e710464db66426daf7a3c41ded2b97037c87969ad8bd0286cdade2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
